language: ruby
rvm:
- 1.9.3
notifications:
  email: false
bundler_args: --deployment
script:
- bundle exec rake db:migrate
- bundle exec rake spec
env:
  global:
  - secure: Ch6JzqQoZs1hzWhxJ/VYYQuIovxsxISFu4/uCoQlplqhWWJ50epP/KyaNKjHyTIAmFfX2gGYF4tCw70fSII1Mvl/lp5aR46JdC1RC79H1n9usJv8GyKWtgcCBSV/cxAeo+XPfKGEgR07loND7AY0u5Mj+ToKwO0zzNzgqvknsTI=
after_success:
- ./heroku.sh
deploy:
  provider: heroku
  api_key:
    secure: IZwKN8VrDWYNaZxjYnhrxjZIa5jZfnrasUjrusOZGNMfcHAqNghCE0bePbHKI6HvE63nhAhib4/o0xNAxF8jg2/H88DhDoaBA/A6DtRNM84ZUbJDTXSIwR/nJukjsoUB2hgYo3LgZ9baJpf36YavGBueo2pX/I/uHTZYqJ6Hghc=
  app: students
  on:
    repo: n774/students
